=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/schema/tests/testDefinition.json
{
  "$id": "https://open-metadata.org/schema/tests/testDefinition.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TestDefinition",
  "description": "TestDefinition is a test definition to capture data quality tests against data entities.",
  "type": "object",
  "javaType": "org.openmetadata.catalog.tests.TestDefinition",
  "javaInterfaces": ["org.openmetadata.catalog.EntityInterface"],
  "definitions": {
    "testPlatform": {
      "javaType": "org.openmetadata.catalog.tests.TestPlatform",
      "description": "This schema defines the platform where tests are defined and ran.",
      "type": "string",
      "enum": [
        "OpenMetadata",
        "GreatExpectations",
        "DBT",
        "Deequ",
        "Soda",
        "Other"
      ]
    },
    "testDataType": {
      "javaType": "org.openmetadata.catalog.type.TestCaseParameterDataType",
      "description": "This enum defines the type of data stored in a column.",
      "type": "string",
      "enum": [
        "NUMBER",
        "INT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "TIMESTAMP",
        "TIME",
        "DATE",
        "DATETIME",
        "ARRAY",
        "MAP",
        "SET",
        "STRING"
      ]
    },
    "entityType": {
      "javaType": "org.openmetadata.catalog.type.TestDefinitionEntityType",
      "description": "This enum defines the type for which this test definition applies to.",
      "type": "string",
      "enum": [
        "TABLE",
        "COLUMN"
      ]
    },
    "testCaseParameterDefinition": {
      "type": "object",
      "javaType": "org.openmetadata.catalog.test.TestCaseParameter",
      "description": "This schema defines the parameters that can be passed for a Test Case.",
      "properties": {
        "name": {
          "description": "name of the parameter.",
          "type": "string"
        },
        "displayName": {
          "description": "Display Name that identifies this parameter name.",
          "type": "string"
        },
        "dataType": {
          "description": "Data type of the parameter (int, date etc.).",
          "$ref": "#/definitions/testDataType"
        },
        "description": {
          "description": "Description of the parameter.",
          "$ref": "../type/basic.json#/definitions/markdown"
        },
        "required": {
          "description": "Is this parameter required.",
          "type": "boolean",
          "default": false
        }
      }
    }
  },
  "properties": {
    "id": {
      "description": "Unique identifier of this test case definition instance.",
      "$ref": "../type/basic.json#/definitions/uuid"
    },
    "name": {
      "description": "Name that identifies this test case.",
      "$ref": "../type/basic.json#/definitions/entityName"
    },
    "displayName": {
      "description": "Display Name that identifies this test case.",
      "type": "string"
    },
    "fullyQualifiedName": {
      "description": "FullyQualifiedName same as `name`.",
      "$ref": "../type/basic.json#/definitions/fullyQualifiedEntityName"
    },
    "description": {
      "description": "Description of the testcase.",
      "$ref": "../type/basic.json#/definitions/markdown"
    },
    "entityType": {
      "$ref": "#/definitions/entityType"
    },
    "testPlatforms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testPlatform"
      }
    },
    "parameterDefinition": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testCaseParameterDefinition"
      }
    },
    "owner": {
      "description": "Owner of this TestCase definition.",
      "$ref": "../type/entityReference.json",
      "default": null
    },
    "version": {
      "description": "Metadata version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/entityVersion"
    },
    "updatedAt": {
      "description": "Last update time corresponding to the new version of the entity in Unix epoch time milliseconds.",
      "$ref": "../type/basic.json#/definitions/timestamp"
    },
    "updatedBy": {
      "description": "User who made the update.",
      "type": "string"
    },
    "href": {
      "description": "Link to the resource corresponding to this entity.",
      "$ref": "../type/basic.json#/definitions/href"
    },
    "changeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "deleted": {
      "description": "When `true` indicates the entity has been soft deleted.",
      "type": "boolean",
      "default": false
    }
  },
  "required": ["name", "description", "testPlatforms"],
  "additionalProperties": false
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/tableColumnCountToEqual.json
{
  "name": "TableColumnCountToEqual",
  "displayName": "TableColumnCountToEqual",
  "description": "This test defines the test TableColumnCountToEqual. Test the number of columns equal to a value.",
  "entityType": "TABLE",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "columnCount",
      "displayName": "ColumnCount",
      "description": "Expected number of columns to equal to a {value}",
      "dataType": "INT",
      "required": true
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValueMinToBeBetween.json
{
    "name": "columnValueMinToBeBetween",
    "displayName": "ColumnValueMinToBeBetween",
    "description": "This schema defines the test ColumnValueMinToBeBetween. Test the minimum value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["OpenMetadata", "GreatExpectations"],
    "parameterDefinition": [
      {
        "name": "minValueForMinInCol",
        "displayName": "minValueForMinInCol",
        "description": "Expected minimum value in the column to be greater or equal than",
        "dataType": "INT"
      },
      {
        "name": "maxValueForMinInCol",
        "displayName": "maxValueForMinInCol",
        "description": "Expect minimum value in the column to be lower or equal than",
        "dataType": "INT"
      }
    ]
  }

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValueMeanToBeBetween.json
{
    "name": "columnValueMeanToBeBetween",
    "displayName": "columnValueMeanToBeBetween",
    "description": "This schema defines the test ColumnValueMeanToBeBetween. Test the mean value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["OpenMetadata", "GreatExpectations"],
    "parameterDefinition": [
    {
      "name": "minValueForMeanInCol",
      "displayName": "minValueForMeanInCol",
      "description": "Expected mean value for the column to be greater or equal than",
      "dataType": "INT"
    },
    {
      "name": "maxValueForMeanInCol",
      "displayName": "maxValueForMeanInCol",
      "description": "Expected mean value for the column to be greater or equal than",
      "dataType": "INT"
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValuesToBeBetween.json
{
  "name": "columnValuesToBeBetween",
  "displayName": "columnValuesToBeBetween",
  "description": "This schema defines the test ColumnValuesToBeBetween. Test the values in a column to be between minimum and maximum value. ",
  "entityType": "COLUMN",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "minValue",
      "displayName": "minValue",
      "description": "The {minValue} value for the column entry. If minValue is not included, maxValue is treated as upperBound and there will be no minimum number of rows",
      "dataType": "INT"
    },
    {
      "name": "maxValue",
      "displayName": "maxValue",
      "description": "The {maxValue} value for the column entry. if maxValue is not included, minValue is treated as lowerBound and there will eb no maximum number of rows",
      "dataType": "INT"
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValuesToBeInSet.json
{
  "name": "ColumnValuesToBeInSet",
  "displayName": "ColumnValuesToBeInSet",
  "description": "This schema defines the test ColumnValuesToBeInSet. Test the column values are in the set.",
  "entityType": "COLUMN",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "allowedValues",
      "displayName": "allowedValues",
      "description": "An Array of values.",
      "dataType": "ARRAY",
      "required": true
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValuesToBeNotNull.json
{
  "name": "columnValuesToBeNotNull",
  "displayName": "columnValuesToBeNotNull",
  "description": "This schema defines the test ColumnValuesToBeNotNull. Test the number of values in a column are null. Values must be explicitly null. Empty strings don't count as null. ",
  "entityType": "COLUMN",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValueStdDevToBeBetween.json
{
    "name": "columnValueStdDevToBeBetween",
    "displayName": "columnValueStdDevToBeBetween",
    "description": "This schema defines the test ColumnValueStdDevToBeBetween. Test the std. dev. value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["OpenMetadata", "GreatExpectations"],
    "parameterDefinition": [
      {
        "name": "minValueForStdDevInCol",
        "displayName": "minValueForStdDevInCol",
        "description": "Expected std. dev value for the column to be greater or equal than",
        "dataType": "INT"
      },
      {
        "name": "maxValueForStdDevInCol",
        "displayName": "maxValueForStdDevInCol",
        "description": "Expected std. dev value for the column to be greater or equal than",
        "dataType": "INT"
      }
    ]
  }

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValuesToBeNotInSet.json
{
  "name": "columnValuesToBeNotInSet",
  "displayName": "columnValuesToBeNotInSet",
  "description": "This schema defines the test ColumnValuesToBeNotInSet. Test the column values to not be in the set. ",
  "entityType": "COLUMN",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "forbiddenValues",
      "displayName": "forbiddenValues",
      "description": "An Array of values.",
      "dataType": "ARRAY",
      "required": true
    }
  ]
}
