=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/schema/tests/testDefinition.json
{
  "$id": "https://open-metadata.org/schema/tests/testDefinition.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TestDefinition",
  "description": "TestDefinition is a test definition to capture data quality tests against data entities.",
  "type": "object",
  "javaType": "org.openmetadata.catalog.tests.TestDefinition",
  "javaInterfaces": ["org.openmetadata.catalog.EntityInterface"],
  "definitions": {
    "testPlatform": {
      "javaType": "org.openmetadata.catalog.tests.TestPlatform",
      "description": "This schema defines the platform where tests are defined and ran.",
      "type": "string",
      "enum": [
        "OpenMetadata",
        "GreatExpectations",
        "DBT",
        "Deequ",
        "Soda",
        "Other"
      ]
    },
    "testDataType": {
      "javaType": "org.openmetadata.catalog.type.TestCaseParameterDataType",
      "description": "This enum defines the type of data stored in a column.",
      "type": "string",
      "enum": [
        "NUMBER",
        "INT",
        "FLOAT",
        "DOUBLE",
        "DECIMAL",
        "TIMESTAMP",
        "TIME",
        "DATE",
        "DATETIME",
        "ARRAY",
        "MAP",
        "SET",
        "STRING"
      ]
    },
    "entityType": {
      "javaType": "org.openmetadata.catalog.type.TestDefinitionEntityType",
      "description": "This enum defines the type for which this test definition applies to.",
      "type": "string",
      "enum": [
        "TABLE",
        "COLUMN"
      ]
    },
    "testCaseParameterDefinition": {
      "type": "object",
      "javaType": "org.openmetadata.catalog.test.TestCaseParameter",
      "description": "This schema defines the parameters that can be passed for a Test Case.",
      "properties": {
        "name": {
          "description": "name of the parameter.",
          "type": "string"
        },
        "displayName": {
          "description": "Display Name that identifies this parameter name.",
          "type": "string"
        },
        "dataType": {
          "description": "Data type of the parameter (int, date etc.).",
          "$ref": "#/definitions/testDataType"
        },
        "description": {
          "description": "Description of the parameter.",
          "$ref": "../type/basic.json#/definitions/markdown"
        },
        "required": {
          "description": "Is this parameter required.",
          "type": "boolean",
          "default": false
        }
      }
    }
  },
  "properties": {
    "id": {
      "description": "Unique identifier of this test case definition instance.",
      "$ref": "../type/basic.json#/definitions/uuid"
    },
    "name": {
      "description": "Name that identifies this test case.",
      "$ref": "../type/basic.json#/definitions/entityName"
    },
    "displayName": {
      "description": "Display Name that identifies this test case.",
      "type": "string"
    },
    "fullyQualifiedName": {
      "description": "FullyQualifiedName same as `name`.",
      "$ref": "../type/basic.json#/definitions/fullyQualifiedEntityName"
    },
    "description": {
      "description": "Description of the testcase.",
      "$ref": "../type/basic.json#/definitions/markdown"
    },
    "entityType": {
      "$ref": "#/definitions/entityType"
    },
    "testPlatforms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testPlatform"
      }
    },
    "parameterDefinition": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/testCaseParameterDefinition"
      }
    },
    "owner": {
      "description": "Owner of this TestCase definition.",
      "$ref": "../type/entityReference.json",
      "default": null
    },
    "version": {
      "description": "Metadata version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/entityVersion"
    },
    "updatedAt": {
      "description": "Last update time corresponding to the new version of the entity in Unix epoch time milliseconds.",
      "$ref": "../type/basic.json#/definitions/timestamp"
    },
    "updatedBy": {
      "description": "User who made the update.",
      "type": "string"
    },
    "href": {
      "description": "Link to the resource corresponding to this entity.",
      "$ref": "../type/basic.json#/definitions/href"
    },
    "changeDescription": {
      "description": "Change that lead to this version of the entity.",
      "$ref": "../type/entityHistory.json#/definitions/changeDescription"
    },
    "deleted": {
      "description": "When `true` indicates the entity has been soft deleted.",
      "type": "boolean",
      "default": false
    }
  },
  "required": ["name", "description", "testPlatforms"],
  "additionalProperties": false
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValuesToNotMatchRegex.json
{
  "name": "columnValuesToNotMatchRegex",
  "displayName": "columnValuesToNotMatchRegex",
  "description": "This schema defines the test ColumnValuesToNotMatchRegex. Test the values in a column to not match a given regular expression. ",
  "entityType": "COLUMN",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "forbiddenRegex",
      "displayName": "forbiddenRegex",
      "description": "The regular expression the column entries should not match.",
      "dataType": "STRING",
      "required": true
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/tableRowCountToEqual.json
{
  "name": "TableRowCountToEqual",
  "displayName": "TableRowCountToEqual",
  "description": "This schema defines the test TableRowCountToEqual. Test the number of rows equal to a value.",
  "entityType": "TABLE",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "value",
      "displayName": "Value",
      "description": "Expected number of rows {value}",
      "dataType": "INT",
      "required": true
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValueMaxToBeBetween.json
{
    "name": "columnValueMaxToBeBetween",
    "displayName": "columnValueMaxToBeBetween",
    "description": "This schema defines the test ColumnValueMaxToBeBetween. Test the maximum value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["OpenMetadata", "GreatExpectations"],
    "parameterDefinition": [
    {
      "name": "minValueForMaxInCol",
      "displayName": "minValueForMaxInCol",
      "description": "Expected maximum value in the column to be greater or equal than",
      "dataType": "INT"
    },
    {
      "name": "maxValueForMaxInCol",
      "displayName": "maxValueForMaxInCol",
      "description": "Expected maximum value in the column to be lower or equal than",
      "dataType": "INT"
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValueMedianToBeBetween.json
{
    "name": "columnValueMedianToBeBetween",
    "displayName": "columnValueMedianToBeBetween",
    "description": "This schema defines the test ColumnValueMedianToBeBetween. Test the median value in a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["OpenMetadata", "GreatExpectations"],
    "parameterDefinition": [
      {
        "name": "minValueForMedianInCol",
        "displayName": "minValueForMedianInCol",
        "description": "Expected median value for the column to be greater or equal than",
        "dataType": "INT"
      },
      {
        "name": "maxColValue",
        "displayName": "maxColValue",
        "description": "Expected median value for the column to be greater or equal than",
        "dataType": "INT"
      }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/tableColumnCountToBeBetween.json
{
  "name": "TableColumnCountToBeBetween",
  "displayName": "TableColumnCountToBeBetween",
  "description": "This schema defines the test TableColumnCountToBeBetween. Test the number of columns to be between min max value.",
  "entityType": "TABLE",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "minColValue",
      "displayName": "minColValue",
      "description": "Expected number of columns should be greater than or equal to {minValue}. If minValue is not included, maxValue is treated as upperBound and there will be no minimum number of column",
      "dataType": "INT"
    },
    {
      "name": "maxColValue",
      "displayName": "maxColValue",
      "description": "Expected number of columns should be less than or equal to {maxValue}. If maxValue is not included, minValue is treated as lowerBound and there will be no maximum number of column",
      "dataType": "INT"
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValuesSumToBeBetween.json
{
    "name": "columnValuesSumToBeBetween",
    "displayName": "columnValuesSumToBeBetween",
    "description": "This schema defines the test ColumnValuesSumToBeBetween. Test the sum of the values of a col is within a range.",
    "entityType": "COLUMN",
    "testPlatforms": ["OpenMetadata", "GreatExpectations"],
    "parameterDefinition": [
      {
        "name": "minValueForColSum",
        "displayName": "minValueForColSum",
        "description": "Expected sum of values in the column to be greater or equal than",
        "dataType": "INT"
      },
      {
        "name": "maxValueForColSum",
        "displayName": "maxValueForColSum",
        "description": "Expected sum values in the column to be lower or equal than",
        "dataType": "INT"
      }
    ]
  }

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/columnValuesMissingCountToBeEqual.json
{
  "name": "columnValuesMissingCount",
  "displayName": "ColumnValuesMissingCount",
  "description": "This schema defines the test ColumnValuesMissingCount. Test the column values missing count to be equal to given number. ",
  "entityType": "COLUMN",
  "testPlatforms": ["OpenMetadata", "GreatExpectations"],
  "parameterDefinition": [
    {
      "name": "missingCountValue",
      "displayName": "missingCountValue",
      "description": "No.of missing values to be equal to.",
      "dataType": "INT",
      "required": true
    },
    {
      "name": "missingValueMatch",
      "displayName": "missingValueMatch",
      "description": "By default match all null and empty values to be missing. This field allows us to configure additional strings such as N/A, NULL as missing strings as well.",
      "dataType": "STRING"
    }
  ]
}

=== parthp2107/OpenMetadata/catalog-rest-service/src/main/resources/json/data/tests/tableColumnNameToExist.json
{
    "name": "TableColumnNameToExist",
    "displayName": "TableColumnNameToExist",
    "description": "This test defines the test TableColumnNameToExist. Test the table columns exists in the table.",
    "entityType": "TABLE",
    "testPlatforms": ["OpenMetadata", "GreatExpectations"],
    "parameterDefinition": [
      {
        "name": "columnName",
        "displayName": "ColumnName",
        "description": "Expected column of the table to exist",
        "dataType": "STRING",
        "required": true
      }
    ]
  }
